/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package easygecng;

import metier.SIReaderHandler;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        
        System.out.println(System.getProperty("java.version"));
        System.out.println( System.getProperty("java.library.path") );

        SIReaderHandler siHandler = new SIReaderHandler(null);

        siHandler.setPortName("COM5");
        siHandler.start();
    }
}
